### PR TITLE
TYPO3 v9 compatibilty

### LINKED ISSUE #6: TYPO3 9 compatible Version
hi,
do you plan to update this extension für TYPO3 9?

### PR DESCRIPTION
**Pull request by markuspoerschke**
Adds compatibilty with v9 by implementing the BE user simulation using the PSR-15 middleware. Therefore a compatibilty with older TYPO3 version is not possible.

I also added a CHANGELOG file and replaced the extension icon.

This will fix #6.

### CODE REVIEW

**Comment by markuspoerschke** [comment]
There is a core bug that is currently blocking this pull request: https://forge.typo3.org/issues/88420

**Comment by CDRO** [comment]
Ok, so we'd have to wait for the next release of TYPO3 9, hopefully 9.5.8.

I'll schedule a release of your new, beautifully rewritten, version two days after the next version is released, so that we both have enough time for testing. Would that be ok for you?

I'll ask Benni Mack if he knows about some approximate time table for this and hope I get an answer.

**Comment by markuspoerschke** [comment]
@CDRO Thanks for your quick response.

Seems my change within the TYPO3 core broke some stuff. Whenever `header()` was called and the intention was to override the value with the PSR-middleware, then there was a breaking change.

Therefore it is still not possible to sent more than one cookies within the middleware. I’ll update the task and try to get in touch with Benni to find a solution how to fix the problem within the core.

**Comment by markuspoerschke** [comment]
The core fix was [merged](https://review.typo3.org/c/Packages/TYPO3.CMS/+/61178/2#message-2982921896a9ee68cd6d39f4eaaf48f57ee241de) to `9.5.x`.

The future TYPO3 version that includes this fix will probably be version 9.5.9, which will be released on August 20.

**Comment by markuspoerschke** [comment]
I adjusted the minumum TYPO3 vesion. From my side this can be merged now. TYPO3 v9.5.9 was released.

**Pull request merged**
